use std::ffi::{c_void, CStr};
use std::os::raw::c_char;

/// An unowned view of a BSON document (the common case: filters, updates, etc.).
#[repr(C)]
#[derive(Copy, Clone)]
pub struct BsonView {
    pub data: *const c_void,
    pub len: usize,
}

// ---------------------------------------------------------------------------
// libbson `bson_value_t` layout — internal Rust mirror, never exported.
//
// Mirrors `bson_value_t` from `<bson/bson-value.h>` so that a `const void *`
// parameter (generated by cbindgen) can be cast and decoded safely.
//
// Layout on 64-bit targets (matches libbson's ABI):
//   offset  0: value_type (u32)
//   offset  4: padding    (i32)
//   offset  8: union      (24 bytes)
//   total   = 32 bytes, alignment = 8
// ---------------------------------------------------------------------------

#[repr(C)]
#[derive(Copy, Clone)]
struct BsonUtf8Value {
    str_ptr: *const c_char,
    /// Byte length including the null terminator.
    len: u32,
}

#[repr(C)]
#[derive(Copy, Clone)]
struct BsonDataValue {
    data: *const u8,
    data_len: u32,
}

#[repr(C)]
union BsonValueUnion {
    v_int32: i32,
    v_int64: i64,
    v_double: f64,
    v_datetime: i64,
    v_bool: u8,
    v_utf8: BsonUtf8Value,
    v_doc: BsonDataValue,
    v_array: BsonDataValue,
    v_oid: [u8; 12],
    /// Ensures the union is wide enough for any libbson variant (24 bytes).
    _pad: [u8; 24],
}

#[repr(C)]
pub(crate) struct BsonValueC {
    value_type: u32,
    _padding: i32,
    value: BsonValueUnion,
}

impl BsonValueC {
    /// Decode a `bson_value_t *` pointer into a [`mongodb::bson::Bson`].
    /// Returns `None` for null, unsupported types, or invalid data.
    pub(crate) unsafe fn ptr_to_bson(ptr: *const BsonValueC) -> Option<mongodb::bson::Bson> {
        unsafe { ptr.as_ref() }?.to_bson()
    }

    fn to_bson(&self) -> Option<mongodb::bson::Bson> {
        use mongodb::bson::{Bson, Document};

        match self.value_type {
            0x01 => Some(Bson::Double(unsafe { self.value.v_double })),
            0x02 => {
                // UTF-8 string
                let utf8 = unsafe { self.value.v_utf8 };
                if utf8.str_ptr.is_null() {
                    return None;
                }
                let s = unsafe { CStr::from_ptr(utf8.str_ptr) }.to_str().ok()?;
                Some(Bson::String(s.to_owned()))
            }
            0x03 => {
                // Embedded document
                let doc = unsafe { self.value.v_doc };
                if doc.data.is_null() {
                    return None;
                }
                let bytes =
                    unsafe { std::slice::from_raw_parts(doc.data, doc.data_len as usize) };
                let document = Document::from_reader(std::io::Cursor::new(bytes)).ok()?;
                Some(Bson::Document(document))
            }
            0x04 => {
                // Array (BSON-encoded as a document with integer-string keys)
                let arr = unsafe { self.value.v_array };
                if arr.data.is_null() {
                    return None;
                }
                let bytes =
                    unsafe { std::slice::from_raw_parts(arr.data, arr.data_len as usize) };
                let document = Document::from_reader(std::io::Cursor::new(bytes)).ok()?;
                let vec: Vec<Bson> = document.into_iter().map(|(_, v)| v).collect();
                Some(Bson::Array(vec))
            }
            0x07 => {
                // ObjectId (12 bytes)
                let oid_bytes: [u8; 12] = unsafe { self.value.v_oid };
                Some(Bson::ObjectId(
                    mongodb::bson::oid::ObjectId::from_bytes(oid_bytes),
                ))
            }
            0x08 => Some(Bson::Boolean(unsafe { self.value.v_bool } != 0)),
            0x09 => {
                // UTC datetime: int64 milliseconds since Unix epoch
                let ms = unsafe { self.value.v_datetime };
                Some(Bson::DateTime(mongodb::bson::DateTime::from_millis(ms)))
            }
            0x0A => Some(Bson::Null),
            0x10 => Some(Bson::Int32(unsafe { self.value.v_int32 })),
            0x12 => Some(Bson::Int64(unsafe { self.value.v_int64 })),
            _ => None,
        }
    }
}
