exec_timeout_secs: 60


tasks:
  - name: test-untar-with-two-dots
    run_on: windows-vsCurrent-small
    commands:
      - command: shell.exec
        params:
          shell: bash
          script: |-
            mkdir with-two-dots
            echo "foo" > with-two-dots/test..txt
      - command: archive.targz_pack
        params:
          target: with-two-dots.tar.gz
          source_dir: with-two-dots
          include: [./**]
      - command: archive.targz_extract
        params:
          destination: untarred
          path: with-two-dots.tar.gz
      

buildvariants:
  - name: run-task
    display_name: "run-task"
    tasks:
      - test-untar-with-two-dots
