# The following task can be run with the `evergreen` CLI as follows:
#   evergreen patch --project=mongo-c-driver \
#     --description="Run example-task" \
#     --yes --finalize \
#      -v example-variant -t example-task

tasks:
  - name: example-task
    run_on: ubuntu2204-small
    commands:
    - command: shell.exec
      params:
        shell: bash
        script: |-
          echo "Hello from example-task!"
  - name: test-asan-cse-sasl-cyrus-openssl-ubuntu2004-clang-compile
    run_on: ubuntu2004-large
    tags: [sanitizers-matrix-asan, compile, ubuntu2004, clang, cse, asan, sasl-cyrus]
    commands:
      - func: cse-sasl-cyrus-openssl-compile
        vars:
          CC: clang
      - func: upload-build
  - name: run-tests-task
    run_on: ubuntu2004-small
    depends_on: [{ name: test-asan-cse-sasl-cyrus-openssl-ubuntu2004-clang-compile }]
    commands:
      - func: fetch-build
        vars:
          BUILD_NAME: test-asan-cse-sasl-cyrus-openssl-ubuntu2004-clang-compile
      - command: expansions.update
        params:
          updates:
            - { key: CC, value: clang }
            - { key: AUTH, value: auth }
            - { key: MONGODB_VERSION, value: "7.0" }
            - { key: TOPOLOGY, value: replica_set }
            - { key: SSL, value: openssl }
            - { key: CLIENT_SIDE_ENCRYPTION, value: "on" }
      - func: fetch-det
      - func: bootstrap-mongo-orchestration
      - func: run-simple-http-server
      - func: run-mock-kms-servers
      - func: run-tests
task_groups:
  - name: testoidc_task_group
    setup_group:
      - func: fetch-det
      - func: "assume ec2 role" # Get necessary AWS credentials
      - command: subprocess.exec
        params:
          binary: bash
          include_expansions_in_env: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]
          args:
            - ./drivers-evergreen-tools/.evergreen/auth_oidc/setup.sh
    setup_group_can_fail_task: true
    setup_group_timeout_secs: 1800
    tasks:
      - example-task
      - test-asan-cse-sasl-cyrus-openssl-ubuntu2004-clang-compile
      - run-tests-task

buildvariants:
  - name: example-variant
    display_name: Example Variant
    tasks:
    - name: testoidc_task_group
