# The following task can be run with the `evergreen` CLI as follows:
#   evergreen patch --project=mongo-c-driver \
#     --description="Run example-task" \
#     --yes --finalize \
#      -v example-variant -t example-task

tasks:
  - name: example-task
    run_on: ubuntu2204-small
    commands:
    - command: shell.exec
      params:
        shell: bash
        script: |-
          echo "Hello from example-task!"

buildvariants:
  - name: example-variant
    display_name: Example Variant
    tasks:
    - example-task
